jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: mq34847.eu-west-1
      user: jeanbaptiste.pinet
      role: ACCOUNTADMIN

      # Keypair config
      private_key_path: /Users/jean-baptiste/Desktop/RSA Snowflake/rsa_key.p8
      # or private_key instead of private_key_path
      private_key_passphrase: snowflakefordbt

      database: RAW
      warehouse: COMPUTE_WH
      schema: JAFFLE_SHOP
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt-core-jb

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None